// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FriendRequestPublic = {
    id: string;
    requester: UserPublic;
    created_at?: (string | null);
};

export type FriendRequestsPublic = {
    data: Array<FriendRequestPublic>;
    count: number;
};

export type FriendshipPublic = {
    id: string;
    user_id: string;
    friend_id: string;
    status: 'pending' | 'accepted';
    created_at?: (string | null);
    responded_at?: (string | null);
};

export type status = 'pending' | 'accepted';

export type FriendsPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type GatheringCreate = {
    place_name: string;
    city: string;
    lat: number;
    lng: number;
    sport_type: 'running' | 'cycling' | 'yoga' | 'stretching' | 'dancing' | 'walking' | 'hiking';
    starts_at: string;
    duration_min: number;
    max_participants: number;
    level: number;
    vibe: Array<('quiet pace' | 'social energy' | 'locked in' | 'reset mode')>;
    description?: (string | null);
    status?: number;
};

export type sport_type = 'running' | 'cycling' | 'yoga' | 'stretching' | 'dancing' | 'walking' | 'hiking';

export type GatheringPublic = {
    id: string;
    host_id: string;
    place_name: string;
    city: string;
    lat: number;
    lng: number;
    sport_type: string;
    starts_at: string;
    duration_min: number;
    max_participants: number;
    level: number;
    vibe: Array<(string)>;
    description: (string | null);
    status: number;
    created_at: (string | null);
    updated_at: (string | null);
};

export type GatheringsPublic = {
    data: Array<GatheringPublic>;
    count: number;
};

export type GatheringUpdate = {
    place_name?: (string | null);
    city?: (string | null);
    lat?: (number | null);
    lng?: (number | null);
    sport_type?: ('running' | 'cycling' | 'yoga' | 'stretching' | 'dancing' | 'walking' | 'hiking' | null);
    starts_at?: (string | null);
    duration_min?: (number | null);
    max_participants?: (number | null);
    level?: (number | null);
    vibe?: (Array<('quiet pace' | 'social energy' | 'locked in' | 'reset mode')> | null);
    description?: (string | null);
    status?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type ParticipantPublic = {
    id: string;
    session_id: string;
    user_id: string;
    status: string;
    joined_at: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (number | null);
    sex?: (number | null);
    city?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (number | null);
    sex?: (number | null);
    city?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    age?: (number | null);
    sex?: (number | null);
    city?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    age?: (number | null);
    sex?: (number | null);
    city?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    age?: (number | null);
    sex?: (number | null);
    city?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type FriendsReadFriendsData = {
    limit?: number;
    skip?: number;
};

export type FriendsReadFriendsResponse = (FriendsPublic);

export type FriendsReadFriendRequestsData = {
    limit?: number;
    skip?: number;
};

export type FriendsReadFriendRequestsResponse = (FriendRequestsPublic);

export type FriendsAddFriendData = {
    friendId: string;
};

export type FriendsAddFriendResponse = (FriendshipPublic);

export type FriendsDeleteFriendData = {
    friendId: string;
};

export type FriendsDeleteFriendResponse = (Message);

export type FriendsAcceptFriendRequestData = {
    requestId: string;
};

export type FriendsAcceptFriendRequestResponse = (Message);

export type FriendsRejectFriendRequestData = {
    requestId: string;
};

export type FriendsRejectFriendRequestResponse = (Message);

export type GatheringsReadGatheringsData = {
    city?: (string | null);
    limit?: number;
    skip?: number;
    sportType?: (string | null);
    status?: (number | null);
};

export type GatheringsReadGatheringsResponse = (GatheringsPublic);

export type GatheringsCreateGatheringData = {
    requestBody: GatheringCreate;
};

export type GatheringsCreateGatheringResponse = (GatheringPublic);

export type GatheringsReadGatheringData = {
    id: string;
};

export type GatheringsReadGatheringResponse = (GatheringPublic);

export type GatheringsUpdateGatheringData = {
    id: string;
    requestBody: GatheringUpdate;
};

export type GatheringsUpdateGatheringResponse = (GatheringPublic);

export type GatheringsDeleteGatheringData = {
    id: string;
};

export type GatheringsDeleteGatheringResponse = (Message);

export type GatheringsJoinGatheringData = {
    gatheringId: string;
};

export type GatheringsJoinGatheringResponse = (ParticipantPublic);

export type GatheringsCancelJoinGatheringData = {
    gatheringId: string;
};

export type GatheringsCancelJoinGatheringResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersSearchUsersData = {
    limit?: number;
    q: string;
    skip?: number;
};

export type UsersSearchUsersResponse = (UsersPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);